# Generated by Django 3.0.2 on 2020-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
